### ISSUE TITLE
Discussion about copyright issue

### ISSUE THREAD

**Issue by fgnm** [rednblackgames/HyperLap2D#12]
Dear @Tom-Ski and @azakhary,
I'm really sorry for misunderstanding that might be created with this repo and my project. Please apologize me if I've done something wrong, I hope that I can clarify the situation.
I've noticed the repository of Overlap2D some months ago, and I've found it deprecated and no more supported. My idea was to relift the whole project and give it a new life. I've never thought to stole anything, moreover I were so thankful to You because create a such good code base where to start.
I've followed, as my best, all licenses present inside the original repository. At time I've forked Overlap2D it was licensed with `Apache 2.0` (https://github.com/UnderwaterApps/overlap2d). I've credit in the `About` section of my project all links to original works licensed with Apache 2.0 I've used, as you can see in this class: https://github.com/rednblackgames/HyperLap2D/blob/a27c2420171c716274fdeece75569426fca74733/src/main/java/games/rednblack/editor/view/ui/dialog/AboutDialog.java#L41
I've preserved all copyright notices and author names in original classes where its was possible (most of originals however): i.e. https://github.com/rednblackgames/HyperLap2D/blob/a27c2420171c716274fdeece75569426fca74733/plugin-performance/src/main/java/games/rednblack/editor/plugin/performance/PerformancePlugin.java#L6 
https://github.com/rednblackgames/HyperLap2D/blob/a27c2420171c716274fdeece75569426fca74733/src/main/java/games/rednblack/editor/view/HyperLap2DScreenMediator.java#L1
Of course, I had to rewrite many classes and done many additions, however these are copyright free, my name is not even there. By default in my IDE when I delete a class or create a new one it has no copyright nor author.

Regarding art assets (https://github.com/rednblackgames/HyperLap2D/tree/master/art) I've removed anything that might be not compatible with Apache 2.0, for example Overlap2D logo, splash screen and so on.
I **never** use something with the intention of stole or something else. As you can see, I've always work with my best intention, I've always admire you for your amazing works, I really want to fix this situation in the most pacific way since I've made this tool just to be useful, nothing more :smiley: 

There might be a issue on the new libGDX's website, where the author uploaded a GIF showing this Editor with some of yours assets. Well, that GIF was only created for demo purpose on libGDX's Discord channel to show members the new feature I were ported from Physics Body Editor (Auto Trace Polygon), but again I've never used it in any other way, it was just a case, I'm really sorry for that, if this was the problem I swear it will never happen again.

In sum, In this repo I've used only stuff mine or licensed with Apache 2.0, if I've done something wrong, please accept my apologies, I'm sure that there will be a solution.

Many thanks for your time.

Sincerely,
Francesco

**Comment by Tom-Ski** [comment]
@fgnm Hey, I appreciate your comments. I would say that this repo currently is missing original AUTHORS file, LICENSE file with copyright notice, which all have to be copied according to apache2. 

e.g.
https://github.com/UnderwaterApps/overlap2d/blob/master/AUTHORS
https://github.com/UnderwaterApps/overlap2d/blob/master/LICENSE
https://github.com/UnderwaterApps/overlap2d/blob/master/CONTRIBUTORS

Aside from missing licensing info that is not intact from the original repo,
there is no mention of anything related to Overlap2D or the original authors in this repo, apart from a small place in code in the about page that you showed. As this project is mostly Overlap2D still at this point, It probably would be at least nice to mention the original authors and repo that this is forked from (since you didn't use github fork).  That said, it is not a requirement, just something nice to do in the foss theme.

From my perspective, I see the rebranding and very sparse accreditation to original authors it doesn't paint a positive picture, but
I can take your word as to no malice and to the misunderstanding.  If you want to remedy these cases I'm happy to include you back onto the site as you continue to bring this relic back to life!

**Comment by fgnm** [comment]
Many thanks for understanding. This is not an excuse, as I was wrong. This is my really first open source project and I've started it in a moment with not so much free time, so I've postponed some stuff in favor of others. Readme and the whole code is still in WIP and I will surely add much more references to Overlap2D in future. For example there will be also a mention in the index of the official website (that again is still WIP and not online yet).

I hope however that this commit could fix this situation fb2970dd17395707f8ea4f64e8256d152a86c24d

Again, I'm so sorry for what have been, you guys really inspire me so much, please don't hesitate to asks me any other modification, question or everything that you consider appropriate.

Thanks!
