### ISSUE TITLE
Project file positions of 0 are ommited

### ISSUE THREAD

**Issue by ambs** [rednblackgames/HyperLap2D#41]
When placing an image in a position where X or Y is 0, the `.dt` file generated doesn't include that field.
While that can be "circumvented", it doesn't make much sense. The file should be the more homogeneous possible, to make its parsing simple as efficient.

**Comment by fgnm** [comment]
Let me explain. Serialization is made using libGDX's Json class that doesn't write fields equals to default.. This behavior is very helpful because it's easy extensible without break backward compatibility plus final json output is smaller.
I can make an option that disable minify but it will not be enable by default.

**Comment by ambs** [comment]
Ah, OK. If there is a good reason, I can understand. No problem.
