### ISSUE TITLE
Need a template project/tutorial for understanding importing to libgdx

### ISSUE THREAD

**Issue by SampuZ** [rednblackgames/HyperLap2D#46]
Hi HyperLap2D team, I made a sample UI design with this tool, but not able to find out any tutorial/template to integrate the design the libgdx project. Could you please make a template project/tutorial for this. Or provide the link if already made. Thanks.

**Comment by fgnm** [comment]
With UI design do you mean HUD/GUI? If so, I generally don't advise to make this kind of stuff with HyperLap2D.. This editor borns to create whatever you need to place object freely in the screen, HUD usually needs constraints, alignment, responsive and so on.. That's why there's integrated Skin Composer plugin: `Window -> Skin Composer`. This is a very great tool made for libGDX's Scene2D that helps you create visually widgets and HUD. This tool it's well documented on its Github page (https://github.com/raeleus/skin-composer), there are also video tutorial (check wiki and tutorial about `Scene Composer` too).

**Comment by SampuZ** [comment]
Sorry not UI design just visual design. I was planning to make a tic-tac-toe with visual effects. If complete tutorial for a simple game can be made available it would be better. Thanks

**Comment by fgnm** [comment]
@SampuZ Here you can find tutorials how to create a simple platformer game with hyperlap and libgdx 

 - YouTube Playlist: https://www.youtube.com/playlist?list=PLtd13r59SKz1GoxM4C-E4oZX7DyOr_3oF
 - Source Code: https://github.com/rednblackgames/tutorial-space-platform

Feel free to join the Discord server if you have any questions or need help https://discord.gg/p69rPNF :)
