### ISSUE TITLE
Feature Request: Support TinyVG

### ISSUE THREAD

**Issue by eGit** [rednblackgames/HyperLap2D#77]
Amazing project!

Would it make sense to support the TinyVG format?

https://github.com/lyze237/gdx-TinyVG

**Comment by fgnm** [comment]
Hi @eGit I did this exactly 4 days ago :D 
TinyVG support is already live in latest SNAPSHOTS, it's an early support so you might find bugs, if any please tell me

**Comment by eGit** [comment]
Thanks! Are you doing the rendering yourself or is TinyVG doing it?

**Comment by fgnm** [comment]
It uses the library made by Lyze for rendering, indeed at runtime level you'll need to include an [extension](https://github.com/rednblackgames/h2d-libgdx-tinyvg-extension) with its dependencies in your libGDX project.

Feel free to join the Discord server if you need more help, I know wiki at moment is quite outdated because most of the things needs to be rewrite for the upcoming first beta release :)
